#!/bin/bash
URL=$1

#apina.biz has some strange urls
if expr $URL : '^http://apina.biz' > /dev/null ; then
  `dirname $0`/loadapina.biz $URL
  exit
fi
if expr $URL : '.*\(.png\|.jpg\|.jpeg\|.gif\)$' > /dev/null ; then
  `dirname $0`/loadimage $URL
  exit
fi
if expr $URL : '^http://imgur.com' > /dev/null ; then
  `dirname $0`/loadimgur $URL
  exit
fi
if expr $URL : '^http://www.hs.fi/fingerpori/' > /dev/null ; then
  `dirname $0`/loadfingerpori $URL
  exit
fi

firefox $URL
