#!/bin/bash

URL=$1
EXTENSION=`echo "$URL" | awk -F . '{print $NF}'`
PROTOCOL=`expr $URL : "\([^:]*\)://"`

if expr "$PROTOCOL" != http \| "$PROTOCOL" != ftp; then
  URL="http://$URL"
fi

if expr $EXTENSION != 'gif' > /dev/null ; then
  feh $URL
  if [ $? == 0 ]; then 
    exit
  fi
fi

#If feh fails or we have a possibly animated gif, download manually 
TMP=`mktemp --suffix=.$EXTENSION`

echo Downloading image from url $URL;

wget -q -O $TMP $URL;
FRAMECOUNT=`identify $TMP | grep GIF | wc -l`
identify $TMP | grep GIF | wc -l

if [ $FRAMECOUNT -gt 1 ]; then
  eog $TMP
else
  feh $TMP
fi
rm $TMP
